name: Update Trieve

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trieve Vitepress Adapter
        run: npm install -g trieve-vitepress-adapter

      - name: Update Trieve Chunks
        env:
          TRIEVE_API_HOST: ${{ secrets.TRIEVE_API_HOST }}
          TRIEVE_API_KEY: ${{ secrets.TRIEVE_API_KEY }}
          TRIEVE_ORGANIZATION_ID: ${{ secrets.TRIEVE_ORGANIZATION_ID }}
          TRIEVE_DATASET_TRACKING_ID: ${{ secrets.TRIEVE_DATASET_TRACKING_ID }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: trieve-vitepress-adapter --path . -s https://coolify.io/docs/openapi.json -r https://coolify.io -a docs/api-reference/api/operations
